name: Create snapshot of Humble Trove data

on:
  schedule:
    - cron: 30 12 * * 3

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: 💾 Cache npm
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: 💾 Cache Next.js
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run create-snapshot

      - name: Commit and push generated snapshot
        uses: EndBug/add-and-commit@v7
        with:
          add: 'data/snapshots'
          default_author: github_actions
          message: "feat(data): create latest snapshot"
